### PR TITLE
180/kiahbuild

### PR DESCRIPTION
**Pull request by david-garza**
Finished KIAH west traffic flow configurations. SIDs and STARs are the ones used for prevailing / light wind operations. SIDs and STARs limited to RNAV and turbojet use. User can now assign instrument approaches to final.

### CODE REVIEW

**Comment by AdamJCavanaugh** [comment]
I'm requesting other reviewers to help, especially since we're essentially replacing an existing airport. I just don't know enough to judge.

**Comment by AdamJCavanaugh** [comment]
From the Discord:

- ARH1

> The new pull is much better, functions fine with all traffic. 
> I do think IAH/HOU need separate initial altitudes. Not sure what it is IRL but the head on departures from 15 IAH 31 HOU is overwhelming at times.
> Also think the downwind fixes DOMNO and BIIGG should be on-map so you can vector to establish a sequence and then put them back on the remainder of the arrival to ease some functions
> there's also a periodic deal where HOU departures will run into each other

- obamna

> I strongly agree, IRL, HOU uses 1 runway for deps, and 1 runway for arrs, the calm wind config is D13R A4
> also, initial altitude for HOU is 5k, IAH is 4k
> All info about the I90, HOU ATCT, and IAH ATCT can be found here: https://www.vzhuids.net/documents-and-controlling-files/sops
> I plan to recreate the boundary to emulate real world, if its okay with OC

**Comment by david-garza** [comment]
ARH1 and obamna,

Thanks for the feedback. 

I really appreciate the feedback on KHOU arrival and departure airports. I live near the JABBS intercept and see arrivals in the afternoon and evening for 13R and it has been a head scratcher trying to figure out the preferred  landing arrivals for KHOU during west flow at KIAH. I will go back to one config with KHOU D13R A4.

Would you want another other KHOU configurations as options?

Clarification for ARH1, do you mean HOWLN instead of BIIGG for the 26L and 27 downwind arrivals? MSCOT, DRLLR, and TEJAS reference HOWLN as the branching point.



So this is what I have so far for improvements:

AIRSPACE

1.  Redefine airspace boundary to match I90, assigned to obamna. (I am fine with with obamna doing this.)

KIAH

1.  Add back DOMNO and HOWLN?/BIIGG? to assign back the STAR for aircraft vectored off for spacing.
2.  Change initial departure altitude from 3,000' to 4,000'

KHOU

1.  Change initial departure altitude from 3,000' to 5,000'
2.  Go back to one config using KHOU D13R and A4. 

I am happy with all of the improvements. Just let me know how you want to handle the branching / merging now that obamna will update the airspace boundary. I don't see any issues with the other 4 outstanding items. And any feedback on the two questions about HOWLN/BIIGG and additional runway configs for KHOU.

Thanks

**Comment by david-garza** [comment]
commit b5f285f incorporates recommendations from the reviewers :

KIAH

-Add DOMNO and HOWLN to assign back the STAR for aircraft vectored off for spacing.
-Change initial departure altitude from 3,000' to 4,000'

KHOU

-Change initial departure altitude from 3,000' to 5,000'
-Go back to one config using KHOU D13R and A4.

Airspace boundary was not changed.

Extra
- I also added a runway configuration 2 that allows for KHOU D22 and A13R
-  Added downwind entries for KHOU 4 and 13R

This should remove traffic conflicts between the airports.

**Comment by ARH1-discord** [comment]
Just tried the new build:

 I think the TEJAS arrival needs to default to the runway 27 transition (this is also the charted default transition IRL) to keep arrivals from swerving across into the north downwind.
 
 I think as a quality of life feature the arrivals can come under control about 90 seconds sooner to allow time to change their approach during peak times. IAH also seems to have a conflict as soon as 15L/R departures become airborne that gets suppressed after a few seconds, not sure what can be done about that.

**Comment by david-garza** [comment]
@ARH1-discord thanks for the feedback. I was aware of the TEJAS STAR defaulting to 26R, but I don't know how Endless ATC selects the default route. The first version of the the KIAH file had the same issue. I tried changing the order of the approaches, but that had no effect on which route is default. @AdamJCavanaugh Adam, do you have any feedback about making a particular approach default?

Obamna is going to update the airspace boundary to match the real life boundary. From what I have seen that should allow more time to change the route for TEJAS arrivals. I also added the HOWLN waypoint, if you miss assigning the inbound aircraft to 27 you can reassign it inbound to HOWLN.

I noticed the 15L/R conflict also, again, not sure how Endless ATC handles simulations departures, but that is annoying that you get docked for for a separation incident before it has been handed off to you.

**Pull request merged**
